# Generated by Django 6.0.3 on 2026-04-06 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etablissements', '0001_initial'),
        ('matieres', '0001_initial'),
        ('scolarite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('absence_justifiee', models.BooleanField(default=False, help_text='Si True, note exclue du calcul de la moyenne CC')),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('EN_ATTENTE', 'En attente de validation')], default='ACTIVE', max_length=20)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='scolarite.inscription')),
                ('matiere_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='matieres.matiereclasse')),
                ('saisi_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'ordering': ['periode__date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ModificationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancienne_valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nouvelle_valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20)),
                ('role_modificateur', models.CharField(blank=True, max_length=30)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif', models.TextField(blank=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_notes', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_notes', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='notes.note')),
            ],
            options={
                'verbose_name': 'Modification de note',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='PeriodeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_periode', models.CharField(choices=[('CONTROLE', 'Contrôle'), ('COMPOSITION', 'Composition'), ('MENSUEL', 'Mensuel'), ('SEMESTRIEL', 'Semestriel')], max_length=20)),
                ('numero', models.PositiveSmallIntegerField()),
                ('libelle', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('saisie_fermee', models.BooleanField(default=False)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='etablissements.anneescolaire')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='etablissements.etablissement')),
            ],
            options={
                'verbose_name': "Période d'évaluation",
                'ordering': ['date_debut'],
                'unique_together': {('etablissement', 'annee_scolaire', 'type_periode', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='note',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.periodeevaluation'),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('inscription', 'matiere_classe', 'periode')},
        ),
    ]
