# Generated by Django 4.2.16 on 2026-04-07 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='delegue_par',
            field=models.ForeignKey(blank=True, help_text='Renseigné si un professeur a délégué la saisie à un surveillant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_deleguees', to=settings.AUTH_USER_MODEL),
        ),
    ]
