# Generated by Django 6.0.3 on 2026-04-06 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigle', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='etablissements/logos/')),
                ('signature_directeur', models.ImageField(blank=True, null=True, upload_to='etablissements/signatures/')),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Série',
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cycle', models.CharField(choices=[('PRESCOLAIRE', 'Préscolaire'), ('ELEMENTAIRE', 'Élémentaire'), ('COLLEGE', 'Collège'), ('LYCEE', 'Lycée')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='etablissements.etablissement')),
            ],
            options={
                'verbose_name': 'Cycle',
                'unique_together': {('etablissement', 'type_cycle')},
            },
        ),
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annees_scolaires', to='etablissements.etablissement')),
            ],
            options={
                'verbose_name': 'Année scolaire',
                'verbose_name_plural': 'Années scolaires',
                'ordering': ['-date_debut'],
                'unique_together': {('etablissement', 'libelle')},
            },
        ),
        migrations.CreateModel(
            name='RegimePedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_controles_par_an', models.PositiveSmallIntegerField(default=3)),
                ('nb_compositions_par_an', models.PositiveSmallIntegerField(default=3)),
                ('seuil_passage', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regime', to='etablissements.cycle')),
            ],
            options={
                'verbose_name': 'Régime pédagogique',
            },
        ),
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('libelle', models.CharField(max_length=100)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jours_feries', to='etablissements.anneescolaire')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jours_feries', to='etablissements.etablissement')),
            ],
            options={
                'verbose_name': 'Jour férié',
                'unique_together': {('etablissement', 'annee_scolaire', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='etablissements.cycle')),
            ],
            options={
                'verbose_name': 'Niveau',
                'ordering': ['cycle', 'ordre'],
                'unique_together': {('cycle', 'nom')},
            },
        ),
    ]
