# Generated by Django 6.0.3 on 2026-04-06 18:58

import apps.scolarite.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etablissements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('effectif_max', models.PositiveSmallIntegerField(default=40)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='etablissements.anneescolaire')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='etablissements.etablissement')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='etablissements.niveau')),
            ],
            options={
                'verbose_name': 'Classe',
                'ordering': ['niveau__ordre', 'nom'],
                'unique_together': {('etablissement', 'annee_scolaire', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(default=apps.scolarite.models.generer_matricule, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=200)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='eleves/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleve', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Élève',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('TRANSFERE', 'Transféré'), ('SORTI', 'Sorti'), ('ADMIS', "Admis (fin d'année)"), ('REDOUBLANT', 'Redoublant')], default='ACTIF', max_length=20)),
                ('code_identification', models.CharField(default=apps.scolarite.models.generer_code_identification, max_length=8, unique=True)),
                ('email_genere', models.EmailField(blank=True, max_length=254)),
                ('decision_passage', models.CharField(blank=True, choices=[('ADMIS', 'Admis'), ('REDOUBLANT', 'Redoublant')], max_length=20)),
                ('motif_decision', models.TextField(blank=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='etablissements.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='scolarite.classe')),
                ('decision_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_passage', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='scolarite.eleve')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='etablissements.etablissement')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etablissements.serie')),
            ],
            options={
                'verbose_name': 'Inscription',
                'ordering': ['-date_inscription'],
                'unique_together': {('eleve', 'annee_scolaire', 'etablissement')},
            },
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('date_effective', models.DateField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('confirme_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_confirmes', to=settings.AUTH_USER_MODEL)),
                ('etablissement_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_entrants', to='etablissements.etablissement')),
                ('initie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_inities', to=settings.AUTH_USER_MODEL)),
                ('inscription_destination', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_entrant', to='scolarite.inscription')),
                ('inscription_origine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfert_sortant', to='scolarite.inscription')),
            ],
            options={
                'verbose_name': 'Transfert',
            },
        ),
        migrations.CreateModel(
            name='LienParentEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.CharField(choices=[('PERE', 'Père'), ('MERE', 'Mère'), ('TUTEUR', 'Tuteur')], default='TUTEUR', max_length=30)),
                ('verifie', models.BooleanField(default=False)),
                ('date_liaison', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='scolarite.eleve')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('parent', 'eleve')},
            },
        ),
    ]
