# Generated by Django 4.2.16 on 2026-04-07 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scolarite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='inscrit_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscription',
            name='motif_rejet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('ACTIF', 'Actif'), ('REJETE', 'Rejeté'), ('TRANSFERE', 'Transféré'), ('SORTI', 'Sorti'), ('ADMIS', "Admis (fin d'année)"), ('REDOUBLANT', 'Redoublant')], default='ACTIF', max_length=20),
        ),
    ]
