# Generated by Django 6.0.3 on 2026-04-06 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matieres', '0001_initial'),
        ('notes', '0001_initial'),
        ('scolarite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('PUBLIE', 'Publié')], default='BROUILLON', max_length=20)),
                ('appreciation_generale', models.TextField(blank=True)),
                ('rang_general', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('effectif_classe', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mention', models.CharField(blank=True, max_length=30)),
                ('nb_absences', models.PositiveSmallIntegerField(default=0)),
                ('nb_retards', models.PositiveSmallIntegerField(default=0)),
                ('bloque', models.BooleanField(default=False)),
                ('motif_blocage', models.TextField(blank=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='bulletins/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='scolarite.inscription')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='notes.periodeevaluation')),
                ('publie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins_publies', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulletin',
                'ordering': ['periode__date_debut'],
                'unique_together': {('inscription', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='BulletinLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('moyenne_cc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note_composition', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('moyenne_matiere', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rang', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('appreciation_prof', models.TextField(blank=True)),
                ('nb_notes_prises_en_compte', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='bulletins.bulletin')),
                ('matiere_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matieres.matiereclasse')),
            ],
            options={
                'unique_together': {('bulletin', 'matiere_classe')},
            },
        ),
    ]
