# Generated by Django 6.0.3 on 2026-04-06 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etablissements', '0001_initial'),
        ('matieres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_horaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('heures_semaine', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='etablissements.anneescolaire')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='etablissements.etablissement')),
                ('matiere_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='matieres.matiereclasse')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affectation professeur',
                'unique_together': {('professeur', 'matiere_classe', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.CharField(blank=True, max_length=50)),
                ('date_effet', models.DateField(help_text='Date à partir de laquelle ce créneau est actif')),
                ('date_fin_effet', models.DateField(blank=True, help_text='Laisser vide si créneau toujours actif', null=True)),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='paie.affectation')),
            ],
            options={
                'verbose_name': 'Emploi du temps',
                'verbose_name_plural': 'Emplois du temps',
            },
        ),
        migrations.CreateModel(
            name='FicheDePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(help_text='Premier jour du mois concerné')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('PROVISOIRE', 'Provisoire'), ('VALIDEE', 'Validée'), ('PAYEE', 'Payée')], default='PROVISOIRE', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_paiement_fiche', models.DateTimeField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='paie/pdfs/')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_de_paie', to='etablissements.etablissement')),
                ('paye_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_payees', to=settings.AUTH_USER_MODEL)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_de_paie', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiche de paie',
                'ordering': ['-mois'],
                'unique_together': {('professeur', 'etablissement', 'mois')},
            },
        ),
        migrations.CreateModel(
            name='LigneFicheDePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures_validees', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('taux_horaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paie.affectation')),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='paie.fichedepaie')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementProfesseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='paie/justificatifs/')),
                ('caissier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_profs_effectues', to=settings.AUTH_USER_MODEL)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_professeurs', to='etablissements.etablissement')),
                ('fiche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='paie.fichedepaie')),
            ],
            options={
                'verbose_name': 'Paiement professeur',
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_seance', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('RATTRAPAGE', 'Rattrapage'), ('REMPLACEMENT', 'Remplacement')], default='PLANIFIEE', max_length=20)),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='paie.affectation')),
                ('emploi_du_temps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='paie.emploidutemps')),
            ],
            options={
                'verbose_name': 'Séance',
                'unique_together': {('emploi_du_temps', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Emargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('RETARD', 'En retard'), ('NON_TENUE', 'Non tenue (jour férié)')], max_length=20)),
                ('heure_debut_reelle', models.TimeField(blank=True, null=True)),
                ('heure_fin_reelle', models.TimeField(blank=True, null=True)),
                ('duree_minutes', models.PositiveSmallIntegerField(default=0)),
                ('observation', models.TextField(blank=True)),
                ('date_emargement', models.DateTimeField(auto_now_add=True)),
                ('emarge_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emargements_effectues', to=settings.AUTH_USER_MODEL)),
                ('seance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emargement', to='paie.seance')),
            ],
            options={
                'verbose_name': 'Émargement',
            },
        ),
    ]
