# Generated by Django 6.0.3 on 2026-04-06 18:58

import apps.finances.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etablissements', '0001_initial'),
        ('scolarite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motif_reduction', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='scolarite.inscription')),
            ],
            options={
                'verbose_name': 'Frais élève',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True)),
                ('caissier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_encaisses', to=settings.AUTH_USER_MODEL)),
                ('frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='finances.frais')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='scolarite.inscription')),
            ],
            options={
                'verbose_name': 'Paiement',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default=apps.finances.models.generer_numero_recu, max_length=20, unique=True)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='recus/pdfs/')),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recu', to='finances.paiement')),
            ],
            options={
                'verbose_name': 'Reçu',
            },
        ),
        migrations.CreateModel(
            name='TypeFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('montant_defaut', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etablissements.anneescolaire')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_frais', to='etablissements.etablissement')),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etablissements.niveau')),
            ],
            options={
                'verbose_name': 'Type de frais',
                'verbose_name_plural': 'Types de frais',
            },
        ),
        migrations.AddField(
            model_name='frais',
            name='type_frais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.typefrais'),
        ),
        migrations.CreateModel(
            name='ClotureCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_encaisse', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_paie_professeurs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_physique', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ecart', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('motif_force', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('CLOTUREE', 'Clôturée'), ('FORCEE', 'Forcée par Directeur')], default='OUVERTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cloture_at', models.DateTimeField(blank=True, null=True)),
                ('caissier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures_effectuees', to=settings.AUTH_USER_MODEL)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clotures_caisse', to='etablissements.etablissement')),
                ('force_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures_forcees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clôture de caisse',
                'ordering': ['-date'],
                'unique_together': {('etablissement', 'date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='frais',
            unique_together={('inscription', 'type_frais')},
        ),
    ]
