# Generated by Django 4.2.16 on 2026-04-07 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('ANNULE', 'Annulé')], default='VALIDE', max_length=10),
        ),
        migrations.CreateModel(
            name='ModificationPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('MODIFICATION', 'Modification de montant'), ('ANNULATION', 'Annulation')], max_length=20)),
                ('motif', models.TextField()),
                ('nouveau_montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_validateur', models.TextField(blank=True)),
                ('demandeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_modif_paiement', to=settings.AUTH_USER_MODEL)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='finances.paiement')),
                ('validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_modif_paiement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de modification de paiement',
                'ordering': ['-date_demande'],
            },
        ),
    ]
