# Generated by Django 6.0.3 on 2026-04-06 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur_email', models.EmailField(blank=True, max_length=254)),
                ('role_au_moment', models.CharField(blank=True, max_length=30)),
                ('etablissement_id_au_moment', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('EXPORT', 'Export'), ('DEBLOCAGE', 'Déblocage élève'), ('VALIDATION', 'Validation'), ('REJET', 'Rejet'), ('TRANSFERT', 'Transfert'), ('CLOTURE', 'Clôture caisse')], max_length=20)),
                ('module', models.CharField(choices=[('NOTES', 'Notes'), ('PAIEMENTS', 'Paiements'), ('BULLETINS', 'Bulletins'), ('PAIE', 'Paie'), ('ELEVES', 'Élèves'), ('UTILISATEURS', 'Utilisateurs'), ('ETABLISSEMENTS', 'Établissements'), ('CAISSE', 'Caisse'), ('SANCTIONS', 'Sanctions'), ('TRANSFERTS', 'Transferts'), ('AUTH', 'Authentification')], max_length=30)),
                ('table_concernee', models.CharField(blank=True, max_length=100)),
                ('enregistrement_id', models.CharField(blank=True, max_length=50)),
                ('anciennes_valeurs', models.JSONField(blank=True, null=True)),
                ('nouvelles_valeurs', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_audit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-date_heure'],
            },
        ),
    ]
