# Generated by Django 6.0.3 on 2026-04-06 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etablissements', '0001_initial'),
        ('paie', '0001_initial'),
        ('scolarite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('justifiee', models.BooleanField(default=False)),
                ('motif', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='scolarite.inscription')),
                ('seance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paie.seance')),
            ],
            options={
                'verbose_name': 'Absence élève',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RetardEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duree_minutes', models.PositiveSmallIntegerField(default=0)),
                ('motif', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retards_enregistres', to=settings.AUTH_USER_MODEL)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retards', to='scolarite.inscription')),
            ],
            options={
                'verbose_name': 'Retard élève',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TypeSanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('gravite', models.PositiveSmallIntegerField(default=1, help_text='1=faible, 5=grave')),
                ('apparait_bulletin_defaut', models.BooleanField(default=False)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_sanctions', to='etablissements.etablissement')),
            ],
            options={
                'verbose_name': 'Type de sanction',
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('motif', models.TextField()),
                ('apparait_bulletin', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='scolarite.inscription')),
                ('prononce_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions_prononcees', to=settings.AUTH_USER_MODEL)),
                ('type_sanction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vie_scolaire.typesanction')),
            ],
            options={
                'verbose_name': 'Sanction',
                'ordering': ['-date'],
            },
        ),
    ]
