# Generated by Django 6.0.3 on 2026-04-06 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('MODIFICATION_NOTE_SOUMISE', 'Modification de note soumise'), ('MODIFICATION_NOTE_VALIDEE', 'Modification de note validée'), ('MODIFICATION_NOTE_REJETEE', 'Modification de note rejetée'), ('BULLETIN_PUBLIE', 'Bulletin publié'), ('FICHE_PAIE_A_VALIDER', 'Fiche de paie à valider'), ('FICHE_PAIE_VALIDEE', 'Fiche de paie validée'), ('PAIEMENT_PROFESSEUR', 'Paiement professeur effectué'), ('ELEVE_DEBLOQUE', 'Élève débloqué'), ('CLOTURE_OUBLIEE', 'Clôture de caisse oubliée'), ('TRANSFERT_ENTRANT', 'Transfert élève entrant'), ('ALERTE_CHUTE_MOYENNE', 'Alerte chute de moyenne'), ('ALERTE_ABSENCE_PROF', 'Alerte taux absence professeur élevé'), ('ALERTE_RETARDS_ELEVE', 'Alerte retards répétés élève'), ('RAPPEL_PAIEMENT', 'Rappel paiement parent'), ('NOTES_NON_SAISIES', 'Notes non saisies — rappel prof')], max_length=50)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('objet_type', models.CharField(blank=True, max_length=50)),
                ('objet_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenFCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_fcm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token FCM',
            },
        ),
    ]
